### PR TITLE
Update javafx-8-tutorial-part7.md

### PR DESCRIPTION
**Pull request by triawarman**

### CODE REVIEW

**Comment by marcojakob** [comment]
Wow, you are awesome @triawarman. It's very good to work with you!

**Comment by marcojakob** [comment]
There are some **description** sentences that are still in English. This is a sentence that is not visible on the website but is important for search engines and is usually displayed when someone shares the site on social media. In the following parts the **description** is still in English, if you want to take a look at it:

* Intro: https://github.com/marcojakob/code.makery.ch/edit/master/collections/library/javafx-8-tutorial-id.md
* Part 1: https://github.com/marcojakob/code.makery.ch/edit/master/collections/library/javafx-8-tutorial-id-part1.md
* Part 2: https://github.com/marcojakob/code.makery.ch/edit/master/collections/library/javafx-8-tutorial-id-part2.md
* Part 4: https://github.com/marcojakob/code.makery.ch/edit/master/collections/library/javafx-8-tutorial-id-part4.md

**Comment by marcojakob** [comment]
One more hint: I've added attribution to your translation at the bottom of the introduction: http://code.makery.ch/library/javafx-8-tutorial/id/

The link points to your google+ profile. If you want to change this you can also send me a pull request with another link.

**Comment by triawarman** [comment]
Nah, i thinking it's better to link to my google+ profile

Thank you.

**Comment by triawarman** [comment]
Done, thanks for the notice.

**Pull request merged**
