### PR TITLE
Correct first intruduction in italian

### PR DESCRIPTION
**Pull request by ksclero**
The first version was worng so i closed the first pull and i create this new introction in italian. Is better and more complete

### CODE REVIEW

**Comment by marcojakob** [comment]
Hi @ksclero. Thank you very much for starting the Italian translation. Looks great!

I've prepared all Italian article pages and included your translation for the introduction. I've also added a link to your GitHub on the introduction page (if you want you can also change this).

* http://code.makery.ch/library/javafx-8-tutorial/it/
* http://code.makery.ch/library/javafx-8-tutorial/it/part1/
* http://code.makery.ch/library/javafx-8-tutorial/it/part2/
* http://code.makery.ch/library/javafx-8-tutorial/it/part3/
* http://code.makery.ch/library/javafx-8-tutorial/it/part4/
* http://code.makery.ch/library/javafx-8-tutorial/it/part5/
* http://code.makery.ch/library/javafx-8-tutorial/it/part6/
* http://code.makery.ch/library/javafx-8-tutorial/it/part7/

Whenever you want to translate you can now go to the Italian article and click on **Edit on GitHub**.

Small hint: It would be nice if you could also translate the `description` sentence in the header info. This is the sentence that usually gets displayed in search engines or when someone shares the article on social media.

Thanks again.
- Marco

**Comment by ksclero** [comment]
yesterday i have translate an half of part 1, but now i can not continue where i left.

i see the half traslation on this link: https://github.com/ksclero/code.makery.ch/commit/5b96d14645d1c0b6af92199ffb7289e90eed696c#diff-b70379bcd5fb69bd3a24f5433ecaf650

is possible to merge with the part 1 so i don't have to restar the traslation?

Date: Fri, 13 Mar 2015 07:18:51 -0700

**Comment by marcojakob** [comment]
I have just updated the tutorial for JDK 8u40 yesterday. There are some small changes in part 1, for example I've removed the link to ControlsFX because that is not necessary any more.

I think the best way would be to work with the new file and copy your translations over, step-by-step. There were not that many changes. You can see them here: https://github.com/marcojakob/code.makery.ch/commit/f6b4a51b41957b753bfbfc8c1f637a6849ceeab5

Sorry... I will not make any changes in the near future, now. But at least the Italian translation will be up to date for JDK 8u40 right from the start ;-)

**Comment by ksclero** [comment]
ok

Date: Fri, 13 Mar 2015 08:11:44 -0700

**Pull request closed without merging**
