### PR TITLE
Updated and rewrited Russian translation

### PR DESCRIPTION
**Pull request by LeonisX**
* Updated and rewrited Russian translation
* Updated sources to latest version (from English tutorial)
* Comments not translated yet

### CODE REVIEW

**Comment by marcojakob** [comment]
Wow, very nice. I just found out that one of my students speaks Russian and he verified that your translation is very good. Thank you. I'm on the road this week, so I will merge it this weekend or beginning next week.

**Comment by LeonisX** [comment]
Thanks :)
Now I again verify text, and translate comments in source code. I hope finish to the end of the week

**Comment by LeonisX** [comment]
OK, done. 

Thanks for such a nice tutorial. Hello from Moldova. Enjoy your holidays. Creative success.

**Comment by marcojakob** [comment]
The updated Russian translation is now live. Thanks again for your work.

**Pull request merged**
