### PR TITLE
Add Korean translatoin for JavaFX 8 Tutorial

### PR DESCRIPTION
**Pull request by olgi3rd**
Add Korean translatoin for JavaFX 8 Tutorial and modify global.json

### CODE REVIEW

**Comment by marcojakob** [comment]
Very nice, thank you @olgi3rd. I will integrate it into the website in the coming days.

**Comment by marcojakob** [comment]
@olgi3rd Wow, that was perfect how you found the relevant files and how you translated everything! That helped a lot for easy integration.

It's now live on: http://code.makery.ch/library/javafx-8-tutorial/kr/

Just curious: What was your motivation for translating? Did you translate it for people you know or just generally, because you think it could benefit people in Korea?

**Comment by olgi3rd** [comment]
@marcojakob I don't know a lot of people but I thought it would be helpful to the people who want to learn JavaFX 8 in Korea. Especially people who don't know English well and also I don't know well.

**Comment by marcojakob** [comment]
@olgi3rd Yes, that's a good point. We should change the date. I would probably change `updated` to the current date. Or what do you think? We could also remove the `updated` date and just have one `date`. What would make sense for you?

**Comment by olgi3rd** [comment]
@marcojakob I think both to be necessary. This tutorials are not newspaper articles, so the date(publication at first) and updated are necessary.

**Comment by marcojakob** [comment]
So, you mean like this:

* date: Apr 19, 2014
* updated: Oct 10, 2016

**Comment by olgi3rd** [comment]
@marcojakob Yes and it should be different for each tutorials.

For Korean tutorial example:

- date: Oct 30, 2016
- updated: Oct 30, 2016

then updated some words:

- date: Oct 30, 2016
- updated: Nov 1, 2016

You might want to put the link to go back to the original tutorial(in this case, English) from every translated tutorials.

How about you?

**Comment by marcojakob** [comment]
It's done. We can add the `updated` date as soon as there are some corrections.

**Pull request merged**
