### PR TITLE
Update javafx-8-tutorial-id.md

### PR DESCRIPTION
**Pull request by triawarman**

### CODE REVIEW

**Comment by marcojakob** [comment]
Very nice work! It's live here: http://code.makery.ch/library/javafx-8-tutorial/id/

If you want you could also translate the `description` sentence in the header. Those are one or two sentences that sometimes appear in search engines and thus makes it easier for people to find what they are looking for.

**Comment by triawarman** [comment]
This is my first time using github and as a translator.
Still dont know what i'm doing, and what part should i translate, need more
learning.

I'll check my translated article one by one after finishing part 7.

**Comment by marcojakob** [comment]
Thank you. I've also integrated part 3, 4, and 5 of your translations.

You are doing great the way you work with GitHub and how you send me the pull requests.

In the zip-File you sent me I saw that you also translated the [Update to JavaFX 8 - What's New?](http://code.makery.ch/blog/update-to-javafx-8-whats-new/) blog post. This is not part of the tutorial series in the library section but in the blog. I currently don't plan to have blog articles in multiple languages because when people subscribe to the blog via RSS they get confused when there are multiple languages. So, if you think the Indonesian translation of the blog article would be useful for other people you are free to put it on a blog of your own, if you want. Just put it on some website and create a link back to my original article. Then let me know when it's ready and I would be glad to also put a link to your website on my page.

**Comment by triawarman** [comment]
I dont have any blog for, maybe later i'll make one and make back link 
to your.

In the future maybe i'll change some part of the translated article if i 
or some one else find my translated words weird haha.

All done, and thank you for letting me translated articles in your blog.

Regards

Triawarman

**Comment by marcojakob** [comment]
Wow, thank you very much. I will add the changes probably tomorrow.

**Pull request merged**
