### PR TITLE
Update javafx-8-tutorial-fr.md

### PR DESCRIPTION
**Pull request by chakram**
First page translated

### CODE REVIEW

**Comment by marcojakob** [comment]
Thank you very much @chakram! I've included your translation and also added you as a contributor on the [first page](http://code.makery.ch/library/javafx-8-tutorial/fr/). If you would like to change your name and link, let me know or change it yourself.

**Comment by marcojakob** [comment]
If you don't mind it would be great if you could also translate the `description` in the meta data of the post. This is used by search results or when someone shares the post on social media:

> description: "This seven-part tutorial walks through designing, programming and deploying an address application with JavaFX."

**Comment by chakram** [comment]
You're welcome. Your tutorials were useful so I thought they also could 
help people speaking only french.

I will try to translate the next part asap.

Best regards

P. "Chakram" Hubscher

**Comment by chakram** [comment]
No problem !  I skipped the headers because I was not familiar with that 
and I was wondering if it was like in HTML (Programming is not my job).

c u

Chak

**Comment by marcojakob** [comment]
The header information (everything before the closing `---`) is in the YAML format. It is used by the templating language to put together pieces of the final HTML page like title, description, sidebar navigation, etc.

**Pull request merged**
