### PR TITLE
javafx 8 tr intro page

### PR DESCRIPTION
**Pull request by alperenkirimer**

### CODE REVIEW

**Comment by marcojakob** [comment]
Very nice! Thank you.

Your translation is now live [here](http://code.makery.ch/library/javafx-8-tutorial/tr/). I have also added an attribution to you at the end. You can also change your name and the link in the attribution if you want.

There is only one small thing that is missing in the translation: 

The `description` sentence: This is the sentence that gets displayed in search results and also if someone shares the site on social media.

**Comment by alperenkirimer** [comment]
Ok, I'll add it as soon as possible

2015-05-17 12:36 GMT+03:00 Marco Jakob <notifications@github.com>:

**Comment by alperenkirimer** [comment]
Hello Marco, I'm sorry about the delays. I have to deal with my final exams
for next two weeks. Then I'll complete the translation.

2015-05-17 19:31 GMT+03:00 Alperen Kırımer <alperenkirimer@gmail.com>:

**Comment by marcojakob** [comment]
Hi. That's perfectly fine!

**Comment by alperenkirimer** [comment]
Hi Marco, finally I'm back.
I will probably finish the whole tutorial less than a month.
So, until that time you can change the Turkish intro page into English
again. It looks ridiculous when it is half Turkish-half English. I will
submit them when the whole tutorial is completed.

2015-05-21 9:30 GMT+03:00 Marco Jakob <notifications@github.com>:

**Comment by alperenkirimer** [comment]
Hello Marco. I have some terrible news.
I saved the pages as doc files and stored them in a usb flash drive to work
offline. Most of them were ready to publish. However the flash drive is
damaged. I am doing my best to recover the files. If I can't save them I'll
start from the beginning.

2015-06-09 8:45 GMT+03:00 Alperen Kırımer <alperenkirimer@gmail.com>:

**Comment by marcojakob** [comment]
Oh, that's a pity. :-( Hope you can recover them somehow.

**Comment by alperenkirimer** [comment]
Dammit. I give up recovering. I'll start from zero again. But I have
learned a great lesson about storing data btw.

2015-07-23 12:49 GMT+03:00 Marco Jakob <notifications@github.com>:

**Comment by marcojakob** [comment]
:-(

**Pull request merged**
